# Generated by Django 6.0.5 on 2026-05-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_email_verification_token_organizerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('icon', models.CharField(default='bi-calendar-event', help_text='e.g. bi-music-note-beamed', max_length=80, verbose_name='Bootstrap Icon name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('is_predefined', models.BooleanField(default=False, help_text='Predefined tags are shown as quick-select chips on the event form.', verbose_name='predefined')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['-is_predefined', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/originals/', verbose_name='banner')),
                ('banner_display', models.ImageField(blank=True, editable=False, help_text='Auto-generated optimized version (1400×520 WebP).', null=True, upload_to='events/banners/display/', verbose_name='display banner')),
                ('timezone', models.CharField(default='Africa/Nairobi', help_text='Event local timezone.', max_length=50, verbose_name='timezone')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=12, verbose_name='status')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True, verbose_name='max capacity')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category', verbose_name='category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.organizerprofile', verbose_name='organizer')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='events.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_reached', models.PositiveSmallIntegerField(default=1, verbose_name='step reached')),
                ('step_data', models.JSONField(default=dict, verbose_name='step data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='events.event', verbose_name='event being edited')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_draft', to='accounts.organizerprofile', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'event draft',
                'verbose_name_plural': 'event drafts',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(default='Tanzania', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('osm_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='OSM ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
                'ordering': ['city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='unique_venue_name_city')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue', verbose_name='venue'),
        ),
        migrations.CreateModel(
            name='EventCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_collaborators', to='accounts.organizerprofile', verbose_name='added by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.event', verbose_name='event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='accounts.organizerprofile', verbose_name='collaborator')),
            ],
            options={
                'verbose_name': 'event collaborator',
                'verbose_name_plural': 'event collaborators',
                'unique_together': {('event', 'organizer')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-starts_at'], name='events_even_status_6ab921_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='events_even_organiz_954d89_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'status', '-starts_at'], name='events_even_is_feat_18a232_idx'),
        ),
    ]
