# Generated by Django 6.0.5 on 2026-05-24 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_email_verification_token_organizerrequest'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Our reference sent to AzamPay as external_id.', unique=True, verbose_name='internal reference')),
                ('provider_ref', models.CharField(blank=True, db_index=True, help_text='AzamPay transaction ID returned in callback.', max_length=255, verbose_name='provider reference')),
                ('provider', models.CharField(choices=[('AZAMPAY_MOBILE', 'AzamPay — Mobile Money'), ('AZAMPAY_CARD', 'AzamPay — Bank Card')], max_length=20, verbose_name='provider')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending — Awaiting Callback'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='INITIATED', max_length=12, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='TZS', max_length=5, verbose_name='currency')),
                ('phone', models.CharField(blank=True, help_text='Mobile number used for USSD push (mobile money only).', max_length=30, verbose_name='phone')),
                ('raw_request', models.JSONField(default=dict, help_text='Payload sent to AzamPay.', verbose_name='raw request payload')),
                ('raw_callback', models.JSONField(blank=True, help_text='Raw POST body received from AzamPay callback.', null=True, verbose_name='raw callback payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='TZS', max_length=5, verbose_name='currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=8, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, help_text='Null = cumulative payout across multiple events.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='events.event', verbose_name='event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounts.organizerprofile', verbose_name='organizer')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_payouts', to=settings.AUTH_USER_MODEL, verbose_name='triggered by')),
            ],
            options={
                'verbose_name': 'organizer payout',
                'verbose_name_plural': 'organizer payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
