# Generated by Django 6.0.5 on 2026-05-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, help_text='Short perks summary, e.g. "Front row + backstage access"', max_length=255, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Set to 0.00 for free tickets.', max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(help_text='Total tickets available for this tier.', verbose_name='total quantity')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='quantity sold')),
                ('max_per_order', models.PositiveSmallIntegerField(default=10, help_text='Maximum tickets a single buyer can purchase in one order.', verbose_name='max per order')),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='sale starts at')),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='sale ends at')),
                ('is_sold_out', models.BooleanField(default=False, help_text='Manually mark as sold out regardless of remaining capacity. Organizer can toggle this at any time.', verbose_name='sold out')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive ticket types are hidden from buyers.', verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'ticket type',
                'verbose_name_plural': 'ticket types',
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
