# Generated by Django 6.0.5 on 2026-05-24 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'guest buyer',
                'verbose_name_plural': 'guest buyers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('FREE', 'Free — No Payment Required')], db_index=True, default='PENDING', max_length=12, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money (USSD)'), ('CARD', 'Bank Card'), ('FREE', 'Free')], max_length=14, verbose_name='payment method')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total paid by buyer before commission deduction.', max_digits=12, verbose_name='gross amount')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Commission deducted by platform.', max_digits=12, verbose_name='platform fee')),
                ('organizer_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount payable to organizer after commission.', max_digits=12, verbose_name='organizer amount')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='Rate applied at time of purchase — snapshot, not live setting.', max_digits=5, verbose_name='commission rate')),
                ('buyer_name', models.CharField(blank=True, max_length=255, verbose_name='buyer name')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='buyer email')),
                ('buyer_phone', models.CharField(blank=True, max_length=30, verbose_name='buyer phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event', verbose_name='event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tickets.guestbuyer', verbose_name='guest buyer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per ticket at time of purchase.', max_digits=10, verbose_name='unit price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.order', verbose_name='order')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tickets.tickettype', verbose_name='ticket type')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('qr_image', models.ImageField(blank=True, editable=False, null=True, upload_to='tickets/qr/', verbose_name='QR code image')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.orderitem', verbose_name='order item')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL, verbose_name='checked in by')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', 'status'], name='tickets_ord_event_i_3c3433_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='tickets_ord_user_id_950c33_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='order_buyer_exactly_one'),
        ),
    ]
